name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}
description: Custom developed factions plugin for custom gamemode
author: geekles
commands:
  factions:
    description: Main alias command for factions. 
    aliases: [f, fac, faction]
    permission: pfacs.use
    usage: /faction [args]

